server:
  port: 8080

spring:
  application:
    name: msvc-food-court-user
  datasource:
    url: jdbc:mysql://localhost/foot_court_user
    username: ${username}
    password: ${password}
  jpa:
    hibernate:
      ddl-auto: update
